name: Documentation

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
    branches:
      - main

# Don't run multiple deployments at once.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    name: Build & deploy docs
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write          # for gh-pages push
      statuses: write          # for documentation status check
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - uses: julia-actions/cache@v2
      - name: Install doc dependencies
        shell: julia --project=docs/ --color=yes {0}
        run: |
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: julia --project=docs/ --color=yes docs/make.jl
